-- =====================================================================
--  학교 캐릭터 공모전 투표 사이트 - Supabase 스키마
-- =====================================================================
--  이 파일 전체를 Supabase 대시보드 → SQL Editor 에 붙여넣고 Run 하면
--  테이블 · RLS(행 단위 보안) 정책 · Storage 버킷 · 함수가 한 번에 만들어집니다.
--
--  ▶ 여러 번 실행해도 안전합니다. (create ... if not exists / create or replace /
--     drop policy if exists 패턴만 사용)  이미 저장된 데이터는 지워지지 않습니다.
--
--  ▶ 보안 설계 요약
--     - 학생은 Supabase "익명 로그인"으로 들어옵니다. (auth.uid() 는 있지만 이메일은 없음)
--     - 학생이 데이터를 "쓰는" 길은 아래 4개 함수뿐입니다.  (SECURITY DEFINER)
--         claim_student  : 학교·학번·이름으로 프로필 만들기/연결하기
--         toggle_like    : 하트 누르기 / 취소
--         add_comment    : 댓글 쓰기
--         delete_my_comment : 내 댓글 지우기
--       함수 안에서 투표 기간, 본인 여부, 글자 수를 다시 검사하므로
--       브라우저 코드를 고쳐도 규칙을 우회할 수 없습니다.
--     - 관리자(교사)는 이메일+비밀번호 계정이며 is_admin() 으로 판별합니다.
--     - 관리자 가입 코드는 secrets 표에만 있고, 브라우저에서는 읽을 수 없습니다.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. 확장 기능
-- ---------------------------------------------------------------------
-- pgcrypto : 관리자 계정을 SQL로 만들 때 비밀번호를 해시(crypt)하기 위해 필요
create extension if not exists pgcrypto with schema extensions;


-- ---------------------------------------------------------------------
-- 1. 테이블
-- ---------------------------------------------------------------------

-- 1-1. settings : 사이트 전체 설정 (행이 딱 1개만 존재)
create table if not exists public.settings (
  id           integer primary key default 1 check (id = 1), -- 항상 1 (단일 행 보장)
  site_title   text not null default '캐릭터 공모전 투표',   -- 사이트 상단 제목
  notice       text not null default '마음에 드는 캐릭터에 하트를 눌러 주세요!', -- 안내문
  voting_open  boolean not null default false,              -- 투표 진행 중 여부 (스위치)
  updated_at   timestamptz not null default now()
);
-- 설정 행이 없으면 기본값으로 1개 만들어 둔다 (이미 있으면 건드리지 않음)
insert into public.settings (id) values (1) on conflict (id) do nothing;


-- 1-2. secrets : 서버 안에서만 쓰는 비밀 값 (관리자 가입 코드 등)
--      RLS 를 켜고 정책을 하나도 만들지 않으므로 브라우저(anon/authenticated)는 절대 읽을 수 없다.
create table if not exists public.secrets (
  key    text primary key,
  value  text not null
);
-- 관리자 가입 코드 기본값 'sonline'. 바꾸려면 SQL Editor 에서
--   update public.secrets set value = '새코드' where key = 'admin_signup_code';
insert into public.secrets (key, value) values ('admin_signup_code', 'sonline')
on conflict (key) do nothing;


-- 1-3. admins : 관리자(교사) 이메일 목록. 여기 있는 이메일로 로그인하면 관리자
create table if not exists public.admins (
  email       text primary key,
  created_at  timestamptz not null default now()
);


-- 1-4. students : 로그인한 학생 프로필
create table if not exists public.students (
  id             uuid primary key default gen_random_uuid(),
  school         text not null,          -- 학생이 입력한 학교 이름 (원문 그대로 보여주기용)
  school_key     text not null,          -- 띄어쓰기/"등학교·학교" 꼬리를 뺀 정규화 값 (중복 비교용)
  student_no     text not null,          -- 학번 (앞뒤 공백 제거)
  name           text not null,          -- 실제 이름 (관리자만 볼 수 있음)
  auth_uid       uuid unique,            -- 현재 연결된 익명 로그인 계정. 다른 기기에서 로그인하면 바뀜
  consent_at     timestamptz not null default now(), -- 개인정보 수집·이용 동의 시각
  created_at     timestamptz not null default now(),
  last_login_at  timestamptz not null default now()
);
-- 같은 (정규화한 학교, 학번) 은 프로필 1개만 허용 → 중복 투표 차단의 핵심
create unique index if not exists students_school_no_uniq
  on public.students (school_key, student_no);


-- 1-5. artworks : 출품작
create table if not exists public.artworks (
  id           uuid primary key default gen_random_uuid(),
  title        text not null,                      -- 작품 제목
  author       text not null default '',           -- 출품자
  description  text not null default '',           -- 작품 설명
  image_path   text not null,                      -- Storage 버킷 안의 파일 경로 (예: 2026/abc.png)
  hidden       boolean not null default false,     -- true 면 학생에게 보이지 않음
  sort_order   integer not null default 0,         -- 관리자 목록 정렬용
  created_at   timestamptz not null default now()
);


-- 1-6. likes : 하트 (작품당 학생 1명 1개)
create table if not exists public.likes (
  id          bigint generated by default as identity primary key,
  artwork_id  uuid not null references public.artworks (id) on delete cascade,
  student_id  uuid not null references public.students (id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (artwork_id, student_id)
);
create index if not exists likes_artwork_idx on public.likes (artwork_id);
create index if not exists likes_student_idx on public.likes (student_id);


-- 1-7. comments : 댓글
create table if not exists public.comments (
  id           bigint generated by default as identity primary key,
  artwork_id   uuid not null references public.artworks (id) on delete cascade,
  student_id   uuid not null references public.students (id) on delete cascade,
  body         text not null check (char_length(body) between 1 and 200), -- 200자 제한 (DB 에서도 검사)
  masked_name  text not null,                       -- 저장 시점에 마스킹한 이름 (예: 강*욱)
  hidden       boolean not null default false,      -- 관리자가 숨긴 댓글
  created_at   timestamptz not null default now()
);
create index if not exists comments_artwork_idx on public.comments (artwork_id);
create index if not exists comments_student_idx on public.comments (student_id);


-- ---------------------------------------------------------------------
-- 2. 보조 함수 (순수 계산용)
-- ---------------------------------------------------------------------

-- 2-1. 학교 이름 정규화
--   "서울 고등학교" → "서울고",  "서울고등학교" → "서울고",  "서울고" → "서울고"
--   "한빛 초등학교" → "한빛초",  "한빛중학교" → "한빛중"
--   규칙: 모든 공백 제거 → 소문자 → 끝의 "등학교" 또는 "학교" 제거
create or replace function public.normalize_school(p_school text)
returns text
language sql
immutable
as $$
  select regexp_replace(
           lower(regexp_replace(coalesce(p_school, ''), '\s+', '', 'g')),
           '(등학교|학교)$', ''
         );
$$;


-- 2-2. 이름 마스킹
--   "강현욱" → "강*욱",  "김민" → "김*",  "남궁민수" → "남**수",  "A" → "*"
create or replace function public.mask_name(p_name text)
returns text
language sql
immutable
as $$
  select case
    when length(n) <= 1 then '*'
    when length(n) = 2  then left(n, 1) || '*'
    else left(n, 1) || repeat('*', length(n) - 2) || right(n, 1)
  end
  from (select trim(coalesce(p_name, '')) as n) s;
$$;


-- ---------------------------------------------------------------------
-- 3. 권한 판별 함수
-- ---------------------------------------------------------------------

-- 3-1. is_admin() : 지금 요청한 사람이 관리자인가?
--   조건 ① 익명 계정이 아님  ② JWT 의 이메일이 admins 표에 있음
--   SECURITY DEFINER 라서 admins 표를 직접 읽을 권한이 없는 역할도 판별만은 가능
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      auth.uid() is not null
      and coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false
      and exists (
        select 1 from public.admins a
        where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
    ), false);
$$;


-- 3-2. my_student_id() : 지금 로그인한 익명 계정에 연결된 학생 프로필 id (없으면 null)
create or replace function public.my_student_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select s.id from public.students s where s.auth_uid = auth.uid() limit 1;
$$;


-- ---------------------------------------------------------------------
-- 4. RLS (행 단위 보안) 켜기 + 정책
-- ---------------------------------------------------------------------
alter table public.settings  enable row level security;
alter table public.secrets   enable row level security;
alter table public.admins    enable row level security;
alter table public.students  enable row level security;
alter table public.artworks  enable row level security;
alter table public.likes     enable row level security;
alter table public.comments  enable row level security;

-- secrets 는 정책이 하나도 없음 → 브라우저에서는 절대 접근 불가 (의도된 설계)
revoke all on public.secrets from anon, authenticated;

-- 4-1. settings : 누구나 읽기, 관리자만 수정
drop policy if exists "settings_read_all"    on public.settings;
drop policy if exists "settings_admin_update" on public.settings;
create policy "settings_read_all"     on public.settings for select using (true);
create policy "settings_admin_update" on public.settings for update
  using (public.is_admin()) with check (public.is_admin());

-- 4-2. admins : 관리자만 목록 조회. 추가/삭제는 함수(signup_admin, remove_admin)로만
drop policy if exists "admins_admin_read" on public.admins;
create policy "admins_admin_read" on public.admins for select using (public.is_admin());

-- 4-3. students : 본인 프로필만 조회 / 관리자는 전체 조회·수정·삭제
--      (학생의 insert/update 는 claim_student 함수로만)
drop policy if exists "students_self_read"   on public.students;
drop policy if exists "students_admin_all"   on public.students;
create policy "students_self_read" on public.students for select
  using (auth_uid = auth.uid());
create policy "students_admin_all" on public.students for all
  using (public.is_admin()) with check (public.is_admin());

-- 4-4. artworks : 숨기지 않은 작품은 누구나(로그인 전 포함) 조회, 관리자는 전부 + 쓰기
drop policy if exists "artworks_read_visible" on public.artworks;
drop policy if exists "artworks_admin_all"    on public.artworks;
create policy "artworks_read_visible" on public.artworks for select
  using (hidden = false or public.is_admin());
create policy "artworks_admin_all" on public.artworks for all
  using (public.is_admin()) with check (public.is_admin());

-- 4-5. likes : 학생은 "내가 누른 하트"만 조회 (전체 개수는 artwork_stats 함수로 제공)
--      관리자는 전체 조회·삭제. 학생의 insert/delete 는 toggle_like 함수로만
drop policy if exists "likes_self_read"  on public.likes;
drop policy if exists "likes_admin_all"  on public.likes;
create policy "likes_self_read" on public.likes for select
  using (student_id = public.my_student_id());
create policy "likes_admin_all" on public.likes for all
  using (public.is_admin()) with check (public.is_admin());

-- 4-6. comments : 숨기지 않은 댓글은 누구나 조회(masked_name 만 노출됨)
--      관리자는 전부 조회 + 숨김/삭제. 학생의 insert/delete 는 함수로만
drop policy if exists "comments_read_visible" on public.comments;
drop policy if exists "comments_admin_all"    on public.comments;
create policy "comments_read_visible" on public.comments for select
  using (hidden = false or public.is_admin());
create policy "comments_admin_all" on public.comments for all
  using (public.is_admin()) with check (public.is_admin());


-- ---------------------------------------------------------------------
-- 5. 학생용 쓰기 함수 (SECURITY DEFINER)
--    브라우저는 supabase.rpc('함수이름', {...}) 로만 호출합니다.
-- ---------------------------------------------------------------------

-- 5-1. claim_student : 학교·학번·이름으로 프로필을 만들거나 기존 프로필에 이 기기를 연결
--   - 미리 등록된 명단 없음 → 누구나 입력하면 참여
--   - 같은 (정규화 학교, 학번) 이 이미 있고 이름이 다르면 거부 (학번 도용 방지)
--   - 이미 있으면 auth_uid 를 지금 기기로 바꿈 → 이전 기기는 더 이상 투표 불가
--   - 반환: 프로필 요약 json
create or replace function public.claim_student(
  p_school     text,
  p_student_no text,
  p_name       text,
  p_consent    boolean
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_school  text := trim(coalesce(p_school, ''));
  v_key     text;
  v_no      text := regexp_replace(trim(coalesce(p_student_no, '')), '\s+', '', 'g');
  v_name    text := regexp_replace(trim(coalesce(p_name, '')), '\s+', '', 'g');
  v_row     public.students%rowtype;
begin
  -- 로그인(익명 포함) 되어 있어야 함
  if v_uid is null then
    raise exception '로그인 정보가 없습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.';
  end if;
  -- 관리자 계정(이메일 계정)으로는 학생 프로필을 만들 수 없음
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false then
    raise exception '학생 로그인은 익명 계정으로만 가능합니다.';
  end if;
  if not coalesce(p_consent, false) then
    raise exception '개인정보 수집·이용에 동의해야 참여할 수 있습니다.';
  end if;
  if v_school = '' or v_no = '' or v_name = '' then
    raise exception '학교, 학번, 이름을 모두 입력해 주세요.';
  end if;
  if char_length(v_school) > 40 or char_length(v_no) > 20 or char_length(v_name) > 20 then
    raise exception '입력값이 너무 깁니다.';
  end if;

  v_key := public.normalize_school(v_school);
  if v_key = '' then
    raise exception '학교 이름을 확인해 주세요.';
  end if;

  -- 같은 학교·학번 프로필이 이미 있는지 확인 (동시 요청 대비 행 잠금)
  select * into v_row
  from public.students
  where school_key = v_key and student_no = v_no
  for update;

  if found then
    -- 이름이 다르면 거부 (공백 제거 후 비교)
    if regexp_replace(v_row.name, '\s+', '', 'g') <> v_name then
      raise exception '이미 다른 이름으로 등록된 학번입니다. 학교·학번·이름을 다시 확인해 주세요.';
    end if;

    -- 이 기기(auth_uid)가 다른 학생 프로필에 연결돼 있었다면 그 연결은 끊음
    update public.students set auth_uid = null
    where auth_uid = v_uid and id <> v_row.id;

    -- 기존 프로필을 지금 기기로 연결 (이전 기기는 투표 불가가 됨)
    update public.students
    set auth_uid = v_uid, last_login_at = now(), school = v_school
    where id = v_row.id
    returning * into v_row;
  else
    -- 이 기기가 다른 프로필에 연결돼 있었다면 끊음 (auth_uid unique 때문에 필요)
    update public.students set auth_uid = null where auth_uid = v_uid;

    insert into public.students (school, school_key, student_no, name, auth_uid)
    values (v_school, v_key, v_no, v_name, v_uid)
    returning * into v_row;
  end if;

  return json_build_object(
    'id',          v_row.id,
    'school',      v_row.school,
    'student_no',  v_row.student_no,
    'name',        v_row.name,
    'masked_name', public.mask_name(v_row.name)
  );
end;
$$;


-- 5-2. toggle_like : 하트 누르기/취소. 반환 { liked: true/false, like_count: n }
create or replace function public.toggle_like(p_artwork_id uuid)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student uuid;
  v_open    boolean;
  v_liked   boolean;
  v_count   integer;
begin
  select voting_open into v_open from public.settings where id = 1;
  if not coalesce(v_open, false) then
    raise exception '지금은 투표 기간이 아닙니다.';
  end if;

  v_student := public.my_student_id();
  if v_student is null then
    raise exception '로그인이 필요합니다. (다른 기기에서 로그인했다면 이 기기는 연결이 해제되었습니다)';
  end if;

  if not exists (select 1 from public.artworks where id = p_artwork_id and hidden = false) then
    raise exception '존재하지 않거나 숨겨진 작품입니다.';
  end if;

  -- 이미 눌렀으면 취소, 아니면 추가
  delete from public.likes where artwork_id = p_artwork_id and student_id = v_student;
  if found then
    v_liked := false;
  else
    insert into public.likes (artwork_id, student_id) values (p_artwork_id, v_student);
    v_liked := true;
  end if;

  select count(*) into v_count from public.likes where artwork_id = p_artwork_id;
  return json_build_object('liked', v_liked, 'like_count', v_count);
end;
$$;


-- 5-3. add_comment : 댓글 작성 (200자 제한, 작성자명은 저장 시점에 마스킹)
--   반환: 방금 저장한 댓글 1건 (학생 화면에 바로 붙이기 위함)
create or replace function public.add_comment(p_artwork_id uuid, p_body text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student public.students%rowtype;
  v_open    boolean;
  v_body    text := trim(coalesce(p_body, ''));
  v_row     public.comments%rowtype;
begin
  select voting_open into v_open from public.settings where id = 1;
  if not coalesce(v_open, false) then
    raise exception '지금은 투표 기간이 아닙니다.';
  end if;

  select * into v_student from public.students where auth_uid = auth.uid();
  if not found then
    raise exception '로그인이 필요합니다. (다른 기기에서 로그인했다면 이 기기는 연결이 해제되었습니다)';
  end if;

  if char_length(v_body) = 0 then
    raise exception '댓글 내용을 입력해 주세요.';
  end if;
  if char_length(v_body) > 200 then
    raise exception '댓글은 200자까지만 쓸 수 있습니다.';
  end if;

  if not exists (select 1 from public.artworks where id = p_artwork_id and hidden = false) then
    raise exception '존재하지 않거나 숨겨진 작품입니다.';
  end if;

  insert into public.comments (artwork_id, student_id, body, masked_name)
  values (p_artwork_id, v_student.id, v_body, public.mask_name(v_student.name))
  returning * into v_row;

  return json_build_object(
    'id',          v_row.id,
    'artwork_id',  v_row.artwork_id,
    'student_id',  v_row.student_id,
    'body',        v_row.body,
    'masked_name', v_row.masked_name,
    'created_at',  v_row.created_at
  );
end;
$$;


-- 5-4. delete_my_comment : 내 댓글만 삭제. 반환: 삭제됐으면 true
create or replace function public.delete_my_comment(p_comment_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student uuid := public.my_student_id();
begin
  if v_student is null then
    raise exception '로그인이 필요합니다.';
  end if;
  delete from public.comments where id = p_comment_id and student_id = v_student;
  return found;
end;
$$;


-- ---------------------------------------------------------------------
-- 6. 읽기용 함수
-- ---------------------------------------------------------------------

-- 6-1. artwork_stats : 작품별 하트 수 · (보이는) 댓글 수. 로그인 전에도 호출 가능
--   likes 표는 학생이 전체를 읽을 수 없으므로 개수는 이 함수로만 제공
create or replace function public.artwork_stats()
returns table (artwork_id uuid, like_count bigint, comment_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select a.id,
         (select count(*) from public.likes l where l.artwork_id = a.id),
         (select count(*) from public.comments c where c.artwork_id = a.id and c.hidden = false)
  from public.artworks a
  where a.hidden = false or public.is_admin();
$$;


-- 6-2. my_profile : 이 기기에 연결된 내 프로필 (없으면 null). 새로고침 후 로그인 상태 복원용
create or replace function public.my_profile()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select json_build_object(
    'id',          s.id,
    'school',      s.school,
    'student_no',  s.student_no,
    'name',        s.name,
    'masked_name', public.mask_name(s.name)
  )
  from public.students s
  where s.auth_uid = auth.uid()
  limit 1;
$$;


-- ---------------------------------------------------------------------
-- 7. 관리자 계정 함수
-- ---------------------------------------------------------------------

-- 7-1. signup_admin : 이메일·비밀번호·가입 코드로 관리자 계정 생성 + 활성화 + 관리자 등록
--   - 이메일 인증 메일을 보내지 않고 auth.users 에 "이미 확인된" 계정을 직접 만든다.
--   - 가입 코드는 secrets 표의 admin_signup_code 와 비교 (브라우저는 코드를 읽을 수 없음)
--   - 이미 같은 이메일 계정이 있으면 비밀번호는 건드리지 않고 관리자 등록만 보장 (재실행 안전)
--   - 로그인 화면(anon) 과 관리자 대시보드(교사 추가) 양쪽에서 같은 함수를 사용
create or replace function public.signup_admin(
  p_email    text,
  p_password text,
  p_code     text
)
returns json
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_email   text := lower(trim(coalesce(p_email, '')));
  v_code    text;
  v_uid     uuid;
  v_created boolean := false;
begin
  if v_email = '' or position('@' in v_email) = 0 then
    raise exception '올바른 이메일을 입력해 주세요.';
  end if;

  select value into v_code from public.secrets where key = 'admin_signup_code';
  if v_code is null or coalesce(p_code, '') <> v_code then
    raise exception '관리자 가입 코드가 올바르지 않습니다.';
  end if;

  select id into v_uid from auth.users where lower(email) = v_email limit 1;

  if v_uid is null then
    if char_length(coalesce(p_password, '')) < 6 then
      raise exception '비밀번호는 6자 이상이어야 합니다.';
    end if;

    v_uid := gen_random_uuid();

    -- auth.users 에 직접 삽입. (빈 문자열 토큰 칼럼들은 null 이면 로그인 시 오류가 나므로 '' 로 채움)
    insert into auth.users (
      instance_id, id, aud, role, email,
      encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data,
      is_super_admin, created_at, updated_at,
      confirmation_token, recovery_token,
      email_change, email_change_token_new, email_change_token_current,
      phone_change, phone_change_token, reauthentication_token,
      is_anonymous
    ) values (
      '00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', v_email,
      extensions.crypt(p_password, extensions.gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
      false, now(), now(),
      '', '',
      '', '', '',
      '', '', '',
      false
    );

    -- 이메일 로그인 identity 도 함께 만들어야 비밀번호 로그인이 된다
    insert into auth.identities (
      id, user_id, provider_id, provider, identity_data,
      last_sign_in_at, created_at, updated_at
    ) values (
      gen_random_uuid(), v_uid, v_uid::text, 'email',
      jsonb_build_object('sub', v_uid::text, 'email', v_email,
                         'email_verified', true, 'phone_verified', false),
      now(), now(), now()
    );
    v_created := true;
  end if;

  -- 관리자 목록에 등록 (이미 있으면 그대로)
  insert into public.admins (email) values (v_email) on conflict (email) do nothing;

  return json_build_object('email', v_email, 'created', v_created);
end;
$$;


-- 7-2. remove_admin : 관리자 권한 해제 (본인은 불가). 로그인 계정 자체는 남지만 관리자 기능 사용 불가
create or replace function public.remove_admin(p_email text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
begin
  if not public.is_admin() then
    raise exception '관리자만 사용할 수 있습니다.';
  end if;
  if v_email = lower(coalesce(auth.jwt() ->> 'email', '')) then
    raise exception '본인의 관리자 권한은 해제할 수 없습니다.';
  end if;
  delete from public.admins where lower(email) = v_email;
  return found;
end;
$$;


-- ---------------------------------------------------------------------
-- 8. 함수 실행 권한 (최소 권한)
--    Supabase 는 기본적으로 모든 함수를 anon/authenticated 가 실행할 수 있게 하므로
--    먼저 전부 회수한 뒤 필요한 역할에만 다시 부여합니다.
-- ---------------------------------------------------------------------
revoke all on function public.normalize_school(text)                     from public, anon, authenticated;
revoke all on function public.mask_name(text)                            from public, anon, authenticated;
revoke all on function public.is_admin()                                 from public, anon, authenticated;
revoke all on function public.my_student_id()                            from public, anon, authenticated;
revoke all on function public.claim_student(text, text, text, boolean)   from public, anon, authenticated;
revoke all on function public.toggle_like(uuid)                          from public, anon, authenticated;
revoke all on function public.add_comment(uuid, text)                    from public, anon, authenticated;
revoke all on function public.delete_my_comment(bigint)                  from public, anon, authenticated;
revoke all on function public.artwork_stats()                            from public, anon, authenticated;
revoke all on function public.my_profile()                               from public, anon, authenticated;
revoke all on function public.signup_admin(text, text, text)             from public, anon, authenticated;
revoke all on function public.remove_admin(text)                         from public, anon, authenticated;

-- RLS 정책 안에서 쓰이므로 로그인 전(anon)에도 실행 가능해야 하는 것들
grant execute on function public.is_admin()        to anon, authenticated;
grant execute on function public.my_student_id()   to anon, authenticated;
grant execute on function public.artwork_stats()   to anon, authenticated;
grant execute on function public.normalize_school(text) to anon, authenticated;
grant execute on function public.mask_name(text)        to anon, authenticated;
-- 관리자 가입은 로그인 전 화면에서 하므로 anon 도 허용 (가입 코드로 보호)
grant execute on function public.signup_admin(text, text, text) to anon, authenticated;
-- 로그인(익명 포함) 후에만 쓰는 것들
grant execute on function public.claim_student(text, text, text, boolean) to authenticated;
grant execute on function public.toggle_like(uuid)                        to authenticated;
grant execute on function public.add_comment(uuid, text)                  to authenticated;
grant execute on function public.delete_my_comment(bigint)                to authenticated;
grant execute on function public.my_profile()                             to authenticated;
grant execute on function public.remove_admin(text)                       to authenticated;


-- ---------------------------------------------------------------------
-- 9. Storage : 작품 이미지 버킷 'artworks'
--    - 공개 버킷 → 이미지 URL 로 누구나 볼 수 있음 (갤러리용)
--    - 업로드/수정/삭제는 관리자만
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('artworks', 'artworks', true, 10485760,  -- 파일당 최대 10MB
        array['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "artworks_bucket_public_read"  on storage.objects;
drop policy if exists "artworks_bucket_admin_insert" on storage.objects;
drop policy if exists "artworks_bucket_admin_update" on storage.objects;
drop policy if exists "artworks_bucket_admin_delete" on storage.objects;

create policy "artworks_bucket_public_read" on storage.objects for select
  using (bucket_id = 'artworks');
create policy "artworks_bucket_admin_insert" on storage.objects for insert
  with check (bucket_id = 'artworks' and public.is_admin());
create policy "artworks_bucket_admin_update" on storage.objects for update
  using (bucket_id = 'artworks' and public.is_admin())
  with check (bucket_id = 'artworks' and public.is_admin());
create policy "artworks_bucket_admin_delete" on storage.objects for delete
  using (bucket_id = 'artworks' and public.is_admin());


-- ---------------------------------------------------------------------
-- 10. 초기 관리자 계정 만들기
--     아래 이메일·비밀번호를 실제 값으로 바꾼 뒤 실행하세요.
--     (이미 같은 이메일이 있으면 비밀번호는 바뀌지 않고 관리자 등록만 됩니다)
-- ---------------------------------------------------------------------
-- select public.signup_admin('teacher@example.com', '비밀번호입력', 'sonline');


-- =====================================================================
--  끝. 이어서 Supabase 대시보드에서 아래 설정을 해 주세요. (README 참고)
--   1) Authentication → Sign In / Providers → Anonymous sign-ins 켜기
--   2) Authentication → Rate Limits → 익명 로그인 제한을 학생 수 이상으로
--   3) (권장) Authentication → Email → Confirm email 끄기
-- =====================================================================
